server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multi?serverTimezone=Asia/Seoul
    username: root
    password: temp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # hibernate 로그 남길지

jwt:
  secret: "dkqorhvmekgkwlaksdltlrksdpanjfajrdmausdksehlrpTwlckawk"
  token:
    access-expiration-time: 9999999
    refresh-expiration-time: 9999999

cors:
  allowed:
    origins: "*"

logging:
  level:
    org:
      hibernate.sql: debug
