spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
---
spring:
  config:
    activate:
      on-profile: local
    import: application-prod.yml, application-domain.yml
#    application-redis-local.yml

---
spring:
  config:
    activate:
      on-profile: prod
#    import: application-prod.yml, application-redis-prod.yml


server:
  port: 8080
