spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE"
  max-age: 3600