spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multi?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: temp
    driver-class-name: com.mysql.cj.jdbc.Driver

# Redission?
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # hibernate 로그 남길지

logging:
  level:
    org.hibernate: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.type: INFO


#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true # hibernate 로그 남길지
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true # hibernate 로그 남길지
#
#logging:
#  level:
#    org.springframework.jdbc: debug